services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  gameserver:
    build:
      context: ./BackEnd/gameServer
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "4000:4000"
    depends_on:
      - database

  authserver:
    build:
      context: ./BackEnd/authServer
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    depends_on:
      - database

  database:
    image: mysql:8
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - gameserver
      - authserver

volumes:
  db_data:
