services:
  frontend:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend1
      - backend2
    environment:
      - REACT_APP_API_URL=http://localhost/api

  backend1:
    build:
      context: .
      dockerfile: ./BackEnd/Dockerfile
    ports:
      - "5001:5000"
    environment:
      - DB_HOST=database1
    depends_on:
      - database1

  backend2:
    build:
      context: .
      dockerfile: ./BackEnd/Dockerfile
    ports:
      - "5002:5000"
    environment:
      - DB_HOST=database2
    depends_on:
      - database2

  database1:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db1
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db1_data:/var/lib/mysql

  database2:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db2
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db2_data:/var/lib/mysql

  revproxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend1
      - backend2

volumes:
  db1_data:
  db2_data:
