version: "3.8"
services:
  frontend1:
    container_name: frontend1-container
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://revproxy/api
    depends_on:
      - revproxy

  frontend2:
    container_name: frontend2-container
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://revproxy/api
    depends_on:
      - revproxy

  authserver1:
    container_name: authserver1-container
    build:
      context: ./backend/authServer
      dockerfile: ./Dockerfile
    ports:
      - "5001:5000"
    environment:
      - DB_HOST=database1
      - DB_NAME=app_db
      - DB_USER=user
      - DB_PASSWORD=password
      - JWT_SECRET=supersecret1
      - AUTH_PORT=5000
    depends_on:
      - database1

  authserver2:
    container_name: authserver2-container
    build:
      context: ./backend/authServer
      dockerfile: ./Dockerfile
    ports:
      - "5002:5000"
    environment:
      - DB_HOST=database2
      - DB_NAME=app_db
      - DB_USER=user
      - DB_PASSWORD=password
      - JWT_SECRET=supersecret2
      - AUTH_PORT=5000
    depends_on:
      - database2

  gameserver1:
    container_name: gameserver1-container
    build:
      context: ./backend/gameServer
      dockerfile: ./Dockerfile
    ports:
      - "4001:4000"
    environment:
      - JWT_SECRET=supersecret1
      - GAME_PORT=4000
    depends_on:
      - authserver1

  gameserver2:
    container_name: gameserver2-container
    build:
      context: ./backend/gameServer
      dockerfile: ./Dockerfile
    ports:
      - "4002:4000"
    environment:
      - JWT_SECRET=supersecret2
      - GAME_PORT=4000
    depends_on:
      - authserver2

  database1:
    container_name: database1-container
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - db1_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - backend

  database2:
    container_name: database2-container
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    depends_on:
      - database1
    volumes:
      - db2_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - backend

  revproxy:
    container_name: revproxy-container
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend1
      - frontend2
      - authserver1
      - authserver2
      - gameserver1
      - gameserver2

volumes:
  db1_data:
  db2_data:

networks:
  backend:
