version: '3.8'
services:
  reverse_proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2

  backend1:
    build:
      context: .
      dockerfile: ./BackEnd/Dockerfile  # Make sure to point to the correct Dockerfile
    environment:
      - DATABASE_HOST=primary_db
    depends_on:
      - primary_db

  backend2:
    build:
      context: . # Use the root context here
      dockerfile: ./BackEnd/Dockerfile  # Same for backend2
    environment:
      - DATABASE_HOST=replica_db
    depends_on:
      - replica_db

  primary_db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password_123
      - MYSQL_DATABASE=dnd
    volumes:
      - primary_data:/var/lib/mysql

  replica_db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password_123
      - MYSQL_DATABASE=dnd
      - PRIMARY_DB_HOST=primary_db
    volumes:
      - replica_data:/var/lib/mysql

  frontend:
    build:
      context: .  # Use the root context here
      dockerfile: ./src/Dockerfile  # Make sure to point to the correct Dockerfile
    depends_on:
      - reverse_proxy

volumes:
  primary_data:
  replica_data:
